# Generated by Django 3.0.3 on 2020-03-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(default='@fudan.edu.cn', max_length=100)),
                ('cookie_value', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
