# Generated by Django 3.0.3 on 2020-04-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200327_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contribution',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.TextField(default='他/她什么也没留下~'),
        ),
    ]
