# Generated by Django 3.0.3 on 2020-04-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200424_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.TextField(default='他(她)什么也没留下~'),
        ),
    ]
