# Generated by Django 3.0.3 on 2020-06-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200430_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.IntegerField(choices=[(0, 'Answertoissue'), (1, 'Commenttoarticle'), (2, 'Commenttoanswer')])),
                ('issue_id', models.IntegerField()),
                ('answer_id', models.IntegerField()),
                ('parent_comment_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('from_uname', models.CharField(default='无名氏', max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('IsReading', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_mes', to='account.User')),
            ],
        ),
    ]
