# Generated by Django 3.0.3 on 2020-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200430_1627'),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='liker',
            new_name='likers',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='liker',
            new_name='likers',
        ),
        migrations.AddField(
            model_name='issue',
            name='collectors',
            field=models.ManyToManyField(related_name='issue_collector', to='account.User'),
        ),
        migrations.DeleteModel(
            name='IssueCollection',
        ),
    ]
