# Generated by Django 3.0.3 on 2020-05-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200430_1627'),
        ('issue', '0002_auto_20200430_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likers',
            field=models.ManyToManyField(related_name='like_answer', to='account.User'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='collectors',
            field=models.ManyToManyField(related_name='collect_issue', to='account.User'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='likers',
            field=models.ManyToManyField(related_name='like_issue', to='account.User'),
        ),
    ]
