# Generated by Django 3.0.3 on 2020-05-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200430_1627'),
        ('issue', '0003_auto_20200505_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_issue', to='account.User'),
        ),
    ]
